99_pjt/01_PJT/06_pjt/skeleton/boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'),   
    path('<int:board_pk>/comment/', views.comment_create, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
]

99_pjt/01_PJT/06_pjt/skeleton/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
]

99_pjt/01_PJT/06_pjt/skeleton/boards/models.py
from django.db import models
from django.conf import settings
# from accounts.models import User
# from django.contrib.auth import get_user_model

# Create your models here.
class Board(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL , on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments') 
    user = models.ForeignKey(settings.AUTH_USER_MODEL , on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    
# related_name='comments'를 빼놨었는데

99_pjt/01_PJT/06_pjt/skeleton/boards/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ('title', 'content', )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

99_pjt/01_PJT/06_pjt/skeleton/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Board, Comment
from .forms import BoardForm, CommentForm
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required

# Create your views here.

## article 부분 
@require_http_methods(["GET"])
def index(request):
    boards = Board.objects.all().order_by('-created_at')
    context = {
        'boards': boards
    }
    return render(request, 'boards/index.html', context)

@require_http_methods(["GET", "POST"])
def detail(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')

    comments = board.comments.all()
    comment_form = CommentForm()
    
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'boards/detail.html', context)

@require_http_methods(["GET", "POST"])
def update(request, pk):
    board = get_object_or_404(Board, pk=pk)

    if request.user == board.user:
        if request.method == 'POST':
            form = BoardForm(request.POST, instance=board)
            if form.is_valid():
                form.save()
                return redirect('boards:detail', board.pk)
        else:
            form = BoardForm(instance=board)
    else:
        return redirect('boards:index')
    
    context = {
        'board': board,
        'form': form,
    }        
    return render(request, 'boards/update.html', context)


# board.user = 현재 로그인된 유저 넣어준 다음에 저장
# commit값에 저장 db에 요청보내지는 않고 저장
# 이후 board.user에 대한 값 넣고, request.user값을 넣는다.

# form.save() form인스턴스 쓰는 이유.
# board는 model 의 인스턴스 form은 modelform의 save modelform은 save되는 순간 생성과 삭제를 구분 가능.

@require_http_methods(["GET", "POST"])
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.user = request.user
            form.save()
            return redirect('boards:index')
    else:
        form = BoardForm()
    context = {
        'form': form,
    }
    return render(request, 'boards/create.html', context)

@login_required
def delete(request, pk):
    board = Board.objects.get(pk=pk)
    if request.user == board.user:
        board.delete()
    return redirect('boards:index')

## comments 부분

@require_http_methods(["POST"])
def comment_create(request, board_pk): #댓글 작성하는 comment_create 코드임.
    board = get_object_or_404(Board, pk=board_pk)
    comment_form = CommentForm(request.POST)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.board = board
            comment.user = request.user
            comment_form.save()
            return redirect('boards:detail', board.pk)
    context = {
        'board':board,
        'comment_form':comment_form
    }        
    return render(request, 'boards/detail.thml', context)

#이전 create부분
# def comments_create(request, pk):
#     board = Board.objects.get(pk=pk)
#     comment_form = CommentForm(request.POST)
#     if comment_form.is_valid():
#         comment = comment_form.save(commit=False)
#         comment.board = board
#         comment.user = request.user
#         comment_form.save()
#         return redirect('boards:detail', board.pk)
#     context = {
#         'board':board,
#         'comment_form':comment_form,
#     }
#     return render(request, 'boards/detail.html', context)

        

@require_http_methods(["POST"])
def comment_detail(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('boards:detail', board_pk)
    
def comment_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('boards:detail', article_pk)
        

99_pjt/01_PJT/06_pjt/skeleton/boards/templates/boards/create.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">생성 페이지</h1>
  <form action="{% url 'boards:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">생성하기</button>
  </form>
</div>
{% endblock content %}

99_pjt/01_PJT/06_pjt/skeleton/boards/templates/boards/detail.html
{% extends 'base.html' %}

{% block content %}
<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">상세 페이지</h1>
  </div>
  <p>글번호 : {{ board.id }}</p>  
  <p>글제목 : {{ board.title }}</p>
  <p>글내용 : {{ board.content }}</p>
  <p>작성날짜 : {{ board.created_at }}</p>
  <p>수정날짜 : {{ board.updated_at }}</p>
  <hr>
  <div class="mb-5 d-flex justify-content-between">
    <a href="{% url 'boards:index' %}"><button class="btn btn-light">메인 페이지로</button></a>
    
    {% comment %} 요청보낸 유저가 작성자 유저 정보랑 일치할 때만 수정/삭제 버튼 띄우기 {% endcomment %}
    {% if request.user == board.user %}
    <div class="d-flex">
      <a href="{% url 'boards:update' board.id %}"><button class="me-3 btn btn-success">수정하기</button></a>
      <form action="{% url 'boards:detail' board.id%}" method='POST'>
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">삭제하기</button>
      </form>
    </div>
    {% endif %}
  </div>

  <form action="{% url 'boards:comment' board.id %}" method='POST'>
    {% csrf_token %}
    <button class="btn btn-secondary" style="float: right;" type="submit">작성하기</button>
    {{ comment_form.as_p }}
  </form>

  <div class="mt-5">
    {% if comments|length == 0 %} 댓글이 없습니다.
    {% else %}
      {% for comment in comments %}
      <div class="my-3 d-flex justify-content-between">
        <div>
          <span>{{ comment.content }}</span>
          <span class="mx-5">({{ comment.created_at }})</span>
        </div>
          <div>
            <form action="{% url 'boards:comment_detail' board.id comment.id %}" method='POST'>
              {% csrf_token %}
              <button class="btn btn-light">삭제하기</button>
            </form>
          </div>
        </div>
        <hr/>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock content %}

99_pjt/01_PJT/06_pjt/skeleton/boards/templates/boards/index.html
{% extends 'base.html' %}

{% block content %}
<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">메인 페이지</h1>
    <a style="height: 70%;" href="{% url 'boards:create' %}"><button class="btn btn-info">생성하기</button></a>
  </div>
  {% if boards|length == 0 %}아직 게시글이 없습니다
  {% else %}
  {% for board in boards %}
    <p>작성자: {{ board.user }}</p>
    <p>글번호 : {{ board.id }}</p>  
    <p>글제목 : <a href="{% url 'boards:detail' board.id %}" style="text-decoration: none;">{{ board.title }}</a></p>
    <hr>
  {% endfor %}
  {% endif %}
</div>
{% endblock content %}

99_pjt/01_PJT/06_pjt/skeleton/boards/templates/boards/update.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">수정 페이지</h1>
  <form action="{% url 'boards:update' board.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정하기">
  </form>
</div>
{% endblock content %}